Q1

In [1]:
import numpy as np

def feedforwardlayer(p, w, b):
    n = np.dot(w, p) + b
    a1 = purelin(n)
    return a1

def purelin(n):
    return n  # This is the identity function, acting as the transfer function (purelin)

# Example usage
p = np.array([[1], [2], [3]])  # Column vector p
w = np.array([[1, 2, 3], [4, 5, 6]])  # Weight matrix w
b = np.array([[1], [2]])  # Bias vector b

a1 = feedforwardlayer(p, w, b)
print(a1)

[[15]
 [34]]


Q2

In [2]:
import numpy as np


def feedforwardlayer(p, w, b):
    n = np.dot(w.T, p) + b
    a1 = purelin(n)
    return a1


def purelin(n):
    return n  # This is the identity function, acting as the transfer function (purelin)


# Prototype patterns
po = np.array([[1], [-1], [-1]])
pa = np.array([[1], [1], [-1]])

# Weight matrix
W1 = np.hstack((po, pa))  # [po, pa]

# Bias vector
b1 = np.array([[3], [3]])

# Input vector
p = np.array([[1], [1], [-1]])

# Feedforward
a1 = feedforwardlayer(p, W1, b1)
print(a1)



[[4]
 [6]]


Q3

In [3]:
import numpy as np

def recurrentlayer(t, a, W):
    if t == 0:
        a2 = a
    else:
        a2 = poslin(np.dot(W, a))
    return a2

def poslin(x):
    return np.maximum(0, x)  # ReLU activation function (poslin)

# Example usage
t = 1  # Timestep
a1 = np.array([[4], [2]])  # Output of the first layer (a1)

# Weight matrix
W2 = np.array([[1, -0.5], [-0.5, 1]])

# Recurrent layer
a2 = recurrentlayer(t, a1, W2)
print(a2)

[[3.]
 [0.]]


Q4

In [4]:
import numpy as np


def recurrentlayer(t, a, W):
    if t == 0:
        a2 = a
    else:
        a2 = poslin(np.dot(W, a))
    return a2


def poslin(x):
    return np.maximum(0, x)  # This is the ReLU activation function (poslin)


# Weight matrix
S = 2  # Number of neurons
𝜺 = 1 / (S - 1)
W2 = np.array([[1, -𝜺], [-𝜺, 1]])

# Initial output of the first layer (a1)
a1 = np.array([[4], [2]])

# Table for t = 0, 1, 2
table = []
for t in range(3):
    a2 = recurrentlayer(t, a1, W2)
    table.append((t, a1.flatten(), a2.flatten()))

# Print the table
print("t\t a1\t\t a2")
for row in table:
    t, a1_val, a2_val = row
    print(f"{t}\t {a1_val}\t {a2_val}")


t	 a1		 a2
0	 [4 2]	 [4 2]
1	 [4 2]	 [2. 0.]
2	 [4 2]	 [2. 0.]


Q5

In [5]:
import numpy as np

def poslin(x):
    return np.maximum(0, x)

def feed_forward_layer(P, W, B):
    X = np.dot(W, P) + B
    return X

def recurrent_layer(A1, W, T):
    if T == 0:
        return A1
    else:
        A2 = A1
        for i in range(1, T+1):
            N = np.dot(W, A2)
            A = [poslin(item) for item in N]
            A2 = A
        return A2

W1 = np.array([[1, -1, -1], [1, 1, -1]])
B1 = np.array([3, 3])
W2 = np.array([[1, -0.5], [-0.5, 1]])
T = 1

inputs = [
    np.array([1, 1, 1]),
    np.array([1, 1, -1]),
    np.array([1, -1, 1]),
    np.array([1, -1, -1]),
    np.array([-1, 1, 1]),
    np.array([-1, 1, -1])
]

for p in inputs:
    a1 = feed_forward_layer(p, W1, B1)
    a2 = recurrent_layer(a1, W2, T)
    print(f"Input: {p}  a2(1): {a2}")

print()

# Additional code for T=2
T = 2

for p in inputs:
    a1 = feed_forward_layer(p, W1, B1)
    a2 = recurrent_layer(a1, W2, T)
    print(f"Input: {p}  a2(2): {a2}")

Input: [1 1 1]  a2(1): [0.0, 3.0]
Input: [ 1  1 -1]  a2(1): [1.0, 4.0]
Input: [ 1 -1  1]  a2(1): [3.0, 0.0]
Input: [ 1 -1 -1]  a2(1): [4.0, 1.0]
Input: [-1  1  1]  a2(1): [0.0, 2.0]
Input: [-1  1 -1]  a2(1): [0.0, 3.0]

Input: [1 1 1]  a2(2): [0.0, 3.0]
Input: [ 1  1 -1]  a2(2): [0.0, 3.5]
Input: [ 1 -1  1]  a2(2): [3.0, 0.0]
Input: [ 1 -1 -1]  a2(2): [3.5, 0.0]
Input: [-1  1  1]  a2(2): [0.0, 2.0]
Input: [-1  1 -1]  a2(2): [0.0, 3.0]


Q5 second way

In [6]:
import numpy as np
from tabulate import tabulate

def feedforward_layer(W1, B1, p):
  """Computes the output of the feedforward layer."""
  a1 = np.dot(p, W1.T) + B1
  a2 = np.where(a1 >= 0, 1, -1)
  return a2

def recurrent_layer(W2, a2):
  """Computes the output of the recurrent layer."""
  a3 = np.dot(a2, W2)
  return a3

def hamming_network(W1, B1, W2, p):
  """Computes the output of the complete Hamming network."""
  a2 = feedforward_layer(W1, B1, p)
  a3 = recurrent_layer(W2, a2)
  while not np.array_equal(a2, a3):
    a2 = a3
    a3 = recurrent_layer(W2, a2)
  return a3

# Test the Hamming network with the given parameters and input values.
W1 = np.array([[1, -1, -1], [1, 1, 1]])
B1 = np.array([[3], [3]])
W2 = np.array([[1, -0.5], [-0.5, 1]])

inputs = [[1, 1, 1], [1, 1, -1], [1, -1, 1], [1, -1, -1], [-1, 1, 1], [-1, 1, -1]]
outputs = []

for p in inputs:
  output = hamming_network(W1, B1, W2, p)
  outputs.append(output)

# Print the output of the Hamming network in a table.
print(tabulate([["Input (p)", "a2(1)", "a2(2)"]] + [[p[0], p[1], p[2]] for p in inputs], headers=["Input (p)", "a2(1)", "a2(2)"], tablefmt="pipe"))


| Input (p)   | a2(1)   | a2(2)   |
|:------------|:--------|:--------|
| Input (p)   | a2(1)   | a2(2)   |
| 1           | 1       | 1       |
| 1           | 1       | -1      |
| 1           | -1      | 1       |
| 1           | -1      | -1      |
| -1          | 1       | 1       |
| -1          | 1       | -1      |
